name: build

on:
  schedule:
    - cron:  '00 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'aur-patches/**'
      - '.github/workflows/build-aur.yaml'
      - 'init-aur-builder.yaml'
      - 'init-aur-patcher.sh'
      - 'README.md'
  workflow_dispatch:
    inputs:
      pkgname:
        description: '(Optional) Pkgname needs to be rebuild '
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install APT packages
        run: sudo apt install -y git python3 python3-yaml

      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: sakarie9/arch-repo
          path: arch-repo/repo

      - name: Clone releases
        run: |
          ./git-clone-releases.sh sakarie9/arch-repo arch-repo/release
          cp -r arch-repo/release arch-repo/release-old

      - name: If rebuild requested
        if: "${{ github.event.inputs.pkgname != '' }}"
        run: |
          pkgbuild_path=pkgbuilds/${{ github.event.inputs.pkgname }}/PKGBUILD
          pkgrel=$(grep '^pkgrel=' $pkgbuild_path | cut -d= -f2)
          pkgrel=$((pkgrel+1))
          sed -i "s/^pkgrel=.*/pkgrel=$pkgrel/" $pkgbuild_path

      - name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.64
        with:
          command: |
            (
              echo ''
              echo '[sakari-aur]'
              echo 'SigLevel = Optional'
              echo 'Server = https://raw.github.com/sakarie9/arch-repo/main/repo'
              # echo ''
              # echo '[archlinuxcn]'
              # echo 'Server = https://mirrors.xtom.hk/archlinuxcn/$arch'
            ) >> /etc/pacman.conf
            # pacman-key --init
            # pacman -Sy --noconfirm archlinuxcn-keyring
            pacman -Sy
            mkdir -p arch-repo/release
            ./git-pkgver-update.sh
            build-pacman-repo build

      - name: Cleanup packages
        run: ./package-cleanup.sh sakari-aur arch-repo/release

      - name: Generate changelog
        run: diff -u <(ls arch-repo/release-old) <(ls arch-repo/release) | tail -n +4 > arch-repo/repo/CHANGELOG

      - name: Upload repo
        env:
          COMMIT_AUTHOR_NAME: ${{ secrets.COMMIT_AUTHOR_NAME }}
          COMMIT_AUTHOR_EMAIL: ${{ secrets.COMMIT_AUTHOR_EMAIL }}
        run: |
          cd arch-repo/repo
          git config --global user.name "$COMMIT_AUTHOR_NAME"
          git config --global user.email "$COMMIT_AUTHOR_EMAIL"

          # # Fresh commit
          # git add -vA
          # if git diff-index --quiet HEAD; then
          #   echo "No changes to commit."
          # else
          #   git checkout --orphan temp_branch
          #   git commit -m "Update by $GITHUB_REPOSITORY@$GITHUB_SHA" 
          #   git branch -D main # delete main branch 
          #   git branch -m main
          #   git push origin main --force
          # fi

          # Normal commit
          git add -vA
          git diff-index --quiet HEAD || git commit -m "Update by $GITHUB_REPOSITORY@$GITHUB_SHA"
          # tag
          if [ $(git tag -l release) ]; then
            git tag -d release
          fi
          git tag release
          # push
          git pull origin main --rebase=true # to avoid conflicts due to data races
          git push origin main

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: "YYYY-MM-DD HH:mm:ss"
          utcOffset: "+08:00"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: sakarie9/arch-repo
          repo_token: ${{ secrets.REPO_TOKEN }}
          file: arch-repo/release/*
          tag: release
          overwrite: true
          file_glob: true
          release_name: ${{ steps.current-time.outputs.formattedTime }}
        

