name: build trigger
on:
  schedule:
    - cron:  '00 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
jobs:
  call-pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: event-pkgbuild
  call-aur:
    if: ${{ always() }} #This will make your workflow2 executed even if workflow1 fails, remove this, if you want to run this only on success of workflow1
    needs: call-pkgbuild
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: event-aur
