name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '00 22 * * *'
  workflow_run:
    workflows: ["trigger"]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install APT packages
        run: sudo apt install -y git python3 python3-yaml

      - name: Clone target repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: xzsk2/arch-repo
          path: arch-repo

      - name: Preprocess PKGBUILDs
        run: ./git-pkgver-update.sh

      - name: Build pacman packages
        uses: pacman-repo-builder/action@0.0.0-rc.64
        with:
          command: |
            (
              echo ''
              echo '[sakari-aur]'
              echo 'SigLevel = Optional'
              echo 'Server = https://raw.github.com/xzsk2/arch-repo/main/repo'
              # echo ''
              # echo '[archlinuxcn]'
              # echo 'Server = https://mirrors.xtom.hk/archlinuxcn/$arch'
            ) >> /etc/pacman.conf
            # pacman-key --init
            # pacman -Sy --noconfirm archlinuxcn-keyring
            pacman -Sy
            mkdir -p arch-repo/repo
            build-pacman-repo build

      - name: Upload packages
        env:
          COMMIT_AUTHOR_NAME: ${{ secrets.COMMIT_AUTHOR_NAME }}
          COMMIT_AUTHOR_EMAIL: ${{ secrets.COMMIT_AUTHOR_EMAIL }}
        run: |
          cd arch-repo
          git config --global user.name "$COMMIT_AUTHOR_NAME"
          git config --global user.email "$COMMIT_AUTHOR_EMAIL"
          git add -v .
          git diff-index --quiet HEAD || git commit -m "Update by $GITHUB_REPOSITORY@$GITHUB_SHA"
          git pull origin main --rebase=true # to avoid conflicts due to data races
          git push origin main