name: build trigger
on:
  schedule:
    - cron:  '00 22 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-pkgbuild:
    uses: ./.github/workflows/build-pkgbuild.yaml
  call-aur:
    if: ${{ always() }} #This will make your workflow2 executed even if workflow1 fails, remove this, if you want to run this only on success of workflow1
    needs: call-workflow1
    uses: ./.github/workflows/build-aur.yaml
