name: nvchecker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-new-versions:
    name: Check New Versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    container:
      image: docker://martynas/archlinux:latest

    steps:
      - name: Set environment variables
        run: |
          sudo chown -R build /github/home
          sudo chown -R build /github/workspace

          echo "LOG_FILE=nvchecker_$(date +'%Y-%m-%d_%H-%M-%S').log" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Check version
        run: |
          pacman -Syu --noconfirm
          pacman -S nvchecker --noconfirm
          nvchecker --logger=json --file nvchecker/config.toml 2>&1 | tee ${{ env.LOG_FILE }}
          #nvcmp --file nvchecker/config.toml > result.tmp
          nvcmp -c nvchecker/config.toml -j > result.json

      - name: Build
        run: |
          packages=$(cat result.json | jq -r '.[].name')
          
          for package in $packages
          do
            pkgbuild_dir=pkgbuilds/${package}
            cd "$pkgbuild_dir"

            makepkg --printsrcinfo > .SRCINFO
            grep -E 'depends' .SRCINFO | \
              sed -e 's/.*depends = //' -e 's/:.*//' | \
              xargs yay -S --noconfirm

            makepkg --syncdeps --noconfirm --install

            source /etc/makepkg.conf # get PKGEXT
            pacman -Qip "${pkgname}"-*"${PKGEXT}"
            pacman -Qlp "${pkgname}"-*"${PKGEXT}"
          done
