name: trigger

on:
  schedule:
    - cron:  '00 00 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ./check-updates.sh
